In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam

In [3]:
pip install kaggle


Note: you may need to restart the kernel to use updated packages.


In [4]:

!kaggle datasets download -d anandkumarsahu09/cattle-breeds-dataset

Dataset URL: https://www.kaggle.com/datasets/anandkumarsahu09/cattle-breeds-dataset
License(s): CC0-1.0
cattle-breeds-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [5]:
!tar -xf cattle-breeds-dataset.zip


In [6]:
import os
import shutil
import random

In [7]:
# Paths
SOURCE_DIR = "cattle Breeds"
TARGET_DIR = "cattle Breeds"

TRAIN_RATIO = 0.7
VAL_RATIO = 0.15
TEST_RATIO = 0.15

random.seed(42)

In [8]:
# Create target folders
for split in ["train", "val", "test"]:
    os.makedirs(os.path.join(TARGET_DIR, split), exist_ok=True)

In [9]:
# Loop through each class
for class_name in os.listdir(SOURCE_DIR):
    class_path = os.path.join(SOURCE_DIR, class_name)

    # Skip train/val/test folders if already created
    if class_name in ["train", "val", "test"]:
        continue

    if not os.path.isdir(class_path):
        continue

    images = os.listdir(class_path)
    random.shuffle(images)

    total = len(images)
    train_end = int(total * TRAIN_RATIO)
    val_end = train_end + int(total * VAL_RATIO)

    splits = {
        "train": images[:train_end],
        "val": images[train_end:val_end],
        "test": images[val_end:]
    }

    for split, split_images in splits.items():
        split_class_dir = os.path.join(TARGET_DIR, split, class_name)
        os.makedirs(split_class_dir, exist_ok=True)

        for img in split_images:
            src = os.path.join(class_path, img)
            dst = os.path.join(split_class_dir, img)
            shutil.copy(src, dst)

print("✅ Train / Validation / Test split completed successfully!")

✅ Train / Validation / Test split completed successfully!


In [10]:
datagen = ImageDataGenerator(
    rescale=1./255,          # normalize pixel values
    rotation_range=10,       # rotate images randomly
    width_shift_range=0.05,   # shift horizontally
    height_shift_range=0.05,  # shift vertically
    zoom_range=0.1,          # random zoomS
    horizontal_flip=True,    # flip horizontally    #
)

# Training data
train_data = datagen.flow_from_directory(
    "cattle Breeds/train",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

val_data = datagen.flow_from_directory(
    "cattle Breeds/val",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

test_data = datagen.flow_from_directory(
    "cattle Breeds/test",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)


Found 843 images belonging to 5 classes.
Found 179 images belonging to 5 classes.
Found 186 images belonging to 5 classes.


In [11]:
print("Training samples:", train_data.samples)
print("Validation samples:", val_data.samples)
num_classes = train_data.num_classes
print("Number of breeds:", num_classes)

Training samples: 843
Validation samples: 179
Number of breeds: 5


In [12]:
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False


In [13]:
for layer in base_model.layers[-30:]:
    if not isinstance(layer, tf.keras.layers.BatchNormalization):   # This line prevents BatchNorm layers from updating, which avoids instability and overfitting when fine-tuning on small datasets.
        layer.trainable = True


In [14]:
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-5)),
    tf.keras.layers.Dropout(0.6),
    tf.keras.layers.Dense(train_data.num_classes, activation='softmax')
])


In [15]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [16]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(           #If validation loss does not improve for 5 consecutive epochs, stop training automatically
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(       #If validation loss stops improving, reduce the learning rate.”
        monitor="val_loss",
        factor=0.2,
        patience=3,
        min_lr=1e-6
    )
]

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=callbacks
)


Epoch 1/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 27s 871ms/step - accuracy: 0.2491 - loss: 1.9222 - val_accuracy: 0.3575 - val_loss: 1.5080 - learning_rate: 1.0000e-05
Epoch 2/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 13s 474ms/step - accuracy: 0.3179 - loss: 1.5942 - val_accuracy: 0.5084 - val_loss: 1.3639 - learning_rate: 1.0000e-05
Epoch 3/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 12s 446ms/step - accuracy: 0.4164 - loss: 1.3965 - val_accuracy: 0.5810 - val_loss: 1.2659 - learning_rate: 1.0000e-05
Epoch 4/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 13s 480ms/step - accuracy: 0.4781 - loss: 1.3082 - val_accuracy: 0.6313 - val_loss: 1.1689 - learning_rate: 1.0000e-05
Epoch 5/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 12s 426ms/step - accuracy: 0.5552 - loss: 1.2051 - val_accuracy: 0.6760 - val_loss: 1.0603 - learning_rate: 1.0000e-05
Epoch 6/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 12s 430ms/step - accuracy: 0.5575 - loss: 1.1344 - val_accuracy: 0.7263 - val_loss: 0.9773 - learning_rate: 1.0000e-05
Epoch 7/10
27/27 ━━━━━━━━━━━━━━━━━━━━ 12s 432ms/step - acc

In [17]:
val_loss, val_acc = model.evaluate(val_data)
print(f"Validation Accuracy after fine-tuning: {val_acc*100:.2f}%")


6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 323ms/step - accuracy: 0.7709 - loss: 0.7660
Validation Accuracy after fine-tuning: 77.09%


In [18]:
y_true = val_data.classes
y_true


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4])

In [19]:
y_pred_probs = model.predict(test_data)
y_pred = np.argmax(y_pred_probs, axis=1)


6/6 ━━━━━━━━━━━━━━━━━━━━ 5s 779ms/step


In [20]:
!pip install scikit-learn
from sklearn.metrics import confusion_matrix

y_true = test_data.classes
cm = confusion_matrix(y_true, y_pred)
print(cm)


[[24  3  7  2  3]
 [ 0 32  2  2  1]
 [ 3  1 35  0  0]
 [ 0 10  1 20  8]
 [ 3  4  1  3 21]]


In [21]:
print(val_data.class_indices)


{'Ayrshire cattle': 0, 'Brown Swiss cattle': 1, 'Holstein Friesian cattle': 2, 'Jersey cattle': 3, 'Red Dane cattle': 4}


In [22]:
from sklearn.metrics import classification_report

print(classification_report(
    y_true,
    y_pred,
    target_names=list(test_data.class_indices.keys())
))


                          precision    recall  f1-score   support

         Ayrshire cattle       0.80      0.62      0.70        39
      Brown Swiss cattle       0.64      0.86      0.74        37
Holstein Friesian cattle       0.76      0.90      0.82        39
           Jersey cattle       0.74      0.51      0.61        39
         Red Dane cattle       0.64      0.66      0.65        32

                accuracy                           0.71       186
               macro avg       0.72      0.71      0.70       186
            weighted avg       0.72      0.71      0.70       186



In [23]:
model.save("cattle_breed_model.keras")


In [25]:
model = tf.keras.models.load_model("cattle_breed_model.keras")

In [26]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("cattle_breed_model.tflite", "wb") as f:
    f.write(tflite_model)


INFO:tensorflow:Assets written to: C:\Users\mural\AppData\Local\Temp\tmp77j5fxmd\assets


INFO:tensorflow:Assets written to: C:\Users\mural\AppData\Local\Temp\tmp77j5fxmd\assets


Saved artifact at 'C:\Users\mural\AppData\Local\Temp\tmp77j5fxmd'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='input_layer_1')
Output Type:
  TensorSpec(shape=(None, 5), dtype=tf.float32, name=None)
Captures:
  2907250961472: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251054144: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251056256: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251049568: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251051856: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251060480: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251099600: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251063296: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251063648: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907251098896: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2907